version: "2"
services:
  ldap:
    image: isx43457566/ldap20:group
    container_name: ldap.edt.org
    hostname: ldap.edt.org
    ports: 
      - "389:389"
      - "636:636"
    networks:
     - 2hisix
  ssh:
    image: isx43457566/ssh20:base
    container_name: ssh.edt.org
    hostname: ssh.edt.org
    ports:
      - "2022:22"
    networks:
     - 2hisix

